"""add admin_added column to reports, but for real

Revision ID: 12a4559e56e4
Revises: 60dbd7870a63
Create Date: 2026-04-20 18:23:42.772852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12a4559e56e4'
down_revision: Union[str, None] = '60dbd7870a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('admin_added', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### end Alembic commands ###
