"""add admin_added column to reports

Revision ID: 60dbd7870a63
Revises: aba6ad2387bc
Create Date: 2026-04-20 18:16:30.155798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60dbd7870a63'
down_revision: Union[str, None] = 'aba6ad2387bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reset_password_tokens_id', table_name='reset_password_tokens')
    op.drop_index('ix_reset_password_tokens_token', table_name='reset_password_tokens')
    op.drop_index('ix_url_reputations_id', table_name='url_reputations')
    op.drop_index('ix_url_reputations_url', table_name='url_reputations')
    op.drop_table('url_reputations')
    op.drop_index('ix_phone_numbers_id', table_name='phone_numbers')
    op.drop_index('ix_phone_numbers_number', table_name='phone_numbers')
    op.drop_index('ix_email_verifications_id', table_name='email_verifications')
    op.drop_index('ix_email_verifications_token', table_name='email_verifications')
    op.drop_index('idx_scans_user_created', table_name='scans')
    op.drop_index('ix_scans_created_at', table_name='scans')
    op.drop_index('ix_scans_id', table_name='scans')
    op.drop_index('idx_reports_user_status', table_name='reports')
    op.drop_index('ix_reports_created_at', table_name='reports')
    op.drop_index('ix_reports_id', table_name='reports')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_reports_id', 'reports', ['id'], unique=False)
    op.create_index('ix_reports_created_at', 'reports', ['created_at'], unique=False)
    op.create_index('idx_reports_user_status', 'reports', ['user_id', 'status'], unique=False)
    op.create_index('ix_scans_id', 'scans', ['id'], unique=False)
    op.create_index('ix_scans_created_at', 'scans', ['created_at'], unique=False)
    op.create_index('idx_scans_user_created', 'scans', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_email_verifications_token', 'email_verifications', ['token'], unique=True)
    op.create_index('ix_email_verifications_id', 'email_verifications', ['id'], unique=False)
    op.create_index('ix_phone_numbers_number', 'phone_numbers', ['number'], unique=True)
    op.create_index('ix_phone_numbers_id', 'phone_numbers', ['id'], unique=False)
    op.create_index('ix_reset_password_tokens_token', 'reset_password_tokens', ['token'], unique=True)
    op.create_index('ix_reset_password_tokens_id', 'reset_password_tokens', ['id'], unique=False)
    # ### end Alembic commands ###
