"""refactored models for postgres compatability

Revision ID: aba6ad2387bc
Revises: 3638c8ebd772
Create Date: 2026-04-18 15:04:51.318755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aba6ad2387bc'
down_revision: Union[str, None] = '3638c8ebd772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
