// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqKj_mPZ3KrkHYcatMQu39KPjuaifvDpk',
    appId: '1:917027421258:web:2455fd61564e0b5d573ab3',
    messagingSenderId: '917027421258',
    projectId: 'cypershieldjo',
    authDomain: 'cypershieldjo.firebaseapp.com',
    storageBucket: 'cypershieldjo.firebasestorage.app',
    measurementId: 'G-C510ZZYVP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI1LvTh8Rnktc2zpQ7abaTa3lSv2dklT0',
    appId: '1:917027421258:android:cabb4915e84fcc57573ab3',
    messagingSenderId: '917027421258',
    projectId: 'cypershieldjo',
    storageBucket: 'cypershieldjo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB31IuIiHDQe56RjZKdf5d_3UPCWqBq2OI',
    appId: '1:917027421258:ios:5462ff0bfcf0547e573ab3',
    messagingSenderId: '917027421258',
    projectId: 'cypershieldjo',
    storageBucket: 'cypershieldjo.firebasestorage.app',
    iosBundleId: 'com.example.cyperShieldJo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB31IuIiHDQe56RjZKdf5d_3UPCWqBq2OI',
    appId: '1:917027421258:ios:5462ff0bfcf0547e573ab3',
    messagingSenderId: '917027421258',
    projectId: 'cypershieldjo',
    storageBucket: 'cypershieldjo.firebasestorage.app',
    iosBundleId: 'com.example.cyperShieldJo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqKj_mPZ3KrkHYcatMQu39KPjuaifvDpk',
    appId: '1:917027421258:web:d110d3c1296640d5573ab3',
    messagingSenderId: '917027421258',
    projectId: 'cypershieldjo',
    authDomain: 'cypershieldjo.firebaseapp.com',
    storageBucket: 'cypershieldjo.firebasestorage.app',
    measurementId: 'G-3HCFH3Q365',
  );
}
